### PR TITLE
Time to leave

### PR DESCRIPTION
**Pull request by mochman**
I don't know if you want this option, but I modified your code to allow people to get a "Leave By" time instead of a duration.  Right now it only works in 24 hour formatted time.  

The user will need to add an 
`arrival_time: '1455',`
to the config section to enable it.

The code makes an initial request to google for a travel time with a `departure_time` of now, it then uses the input arrival time minus the travel time for a new `departure_time` to get a more realistic travel time based on predicted traffic.  The module then displays "Leave by 0000" to the user.

### CODE REVIEW

**Comment by SamLewis0602** [comment]
That's a clever workaround for the lack of support for `arrival_time` in the Maps API. I'm not sure why it's not supported considering it's an option on the Google Maps web interface. Great work!

**Comment by SamLewis0602** [comment]
This merge is broken. It does not function properly when arrival_time is not set. Please help me debug this immediately as I can't revert the pull request.

**Comment by mochman** [comment]
Could you send me your config.js section without the API key.  I just tried it with out the arrival_time and it gives me the normal time to commute.

**Comment by mochman** [comment]
If that still doesn't fix the problem, I have your original without my edits I can send you a pull request for to reset it all.

**Comment by SamLewis0602** [comment]
I already fixed it. Look at the commits I've made. If the arrival_time wasn't set it wouldn't revert to the original style. You were checking for `if this.leaveBy = ''` in `getDom` instead of `if this.config.arrival_time = ''`. Also, you have to include the api url in the response from node_helper so that the modules can differentiate between notifications for them and notifications for other instances of the same module.

**Comment by SamLewis0602** [comment]
Not a big deal, I should have checked more thoroughly before merging the request. Learning experience for both of us 😄

**Comment by mochman** [comment]
Sorry about all that.  I get it working for what I need and fail to do some testing before I send it out.

**Comment by SamLewis0602** [comment]
No problem. The module has grown quite a bit, there's a lot to test. And when I was originally developing it MichMich had to point out to me that I needed to account for having multiple instances of the same module on there. Only way to learn is to get your hands dirty!

**Pull request merged**
